/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_jbig_JBigConvert */

#ifndef _Included_com_android_jbig_JBigConvert
#define _Included_com_android_jbig_JBigConvert
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_android_jbig_JBigConvert
 * Method:    decompressing
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_android_jbig_JBigConvert_decompressing
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_android_jbig_JBigConvert
 * Method:    compressing
 * Signature: (Landroid/graphics/Bitmap;[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_android_jbig_JBigConvert_compressing
  (JNIEnv *, jobject, jobject, jbyteArray);

/*
 * Class:     com_android_jbig_JBigConvert
 * Method:    compressingWH
 * Signature: (II[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_android_jbig_JBigConvert_compressingWH
  (JNIEnv *, jobject, jint, jint, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
